/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    leads: Lead;
    facts: Fact;
    directions: Direction;
    stages: Stage;
    reviews: Review;
    cases: Case;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    facts: FactsSelect<false> | FactsSelect<true>;
    directions: DirectionsSelect<false> | DirectionsSelect<true>;
    stages: StagesSelect<false> | StagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'automation-page': AutomationPage;
    integrations: Integration;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'automation-page': AutomationPageSelect<false> | AutomationPageSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  contact: string;
  message: string;
  source?: string | null;
  status?: ('new' | 'in_progress' | 'contacted' | 'qualified' | 'closed') | null;
  assignee?: (number | null) | User;
  /**
   * Не показывается на сайте
   */
  internalNotes?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  landingPage?: string | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facts".
 */
export interface Fact {
  id: number;
  title?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  titleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  textRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  value?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  valueRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visible?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions".
 */
export interface Direction {
  id: number;
  title?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  titleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  textRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  number?: string | null;
  eyebrow?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  eyebrowRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  outcomes?:
    | {
        text?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        textRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        titleRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        text?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        textRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        points?:
          | {
              text?: string | null;
              /**
               * H1–H6, абзацы, ссылки, жирный, курсив и списки.
               */
              textRichText?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  visible?: boolean | null;
  order?: number | null;
  seo?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    descriptionRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages".
 */
export interface Stage {
  id: number;
  title?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  titleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  textRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  visible?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  titleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  textRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  author?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  authorRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  company?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  companyRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  role?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  roleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visible?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  titleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  textRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  slug: string;
  client?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  clientRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metrics?:
    | {
        value?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        valueRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        label?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        labelRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  visible?: boolean | null;
  order?: number | null;
  seo?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    descriptionRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  titleRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  text?: string | null;
  /**
   * H1–H6, абзацы, ссылки, жирный, курсив и списки.
   */
  textRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  slug: string;
  price?: string | null;
  features?:
    | {
        text?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        textRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  visible?: boolean | null;
  order?: number | null;
  seo?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    descriptionRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'facts';
        value: number | Fact;
      } | null)
    | ({
        relationTo: 'directions';
        value: number | Direction;
      } | null)
    | ({
        relationTo: 'stages';
        value: number | Stage;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  message?: T;
  source?: T;
  status?: T;
  assignee?: T;
  internalNotes?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  landingPage?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facts_select".
 */
export interface FactsSelect<T extends boolean = true> {
  title?: T;
  titleRichText?: T;
  text?: T;
  textRichText?: T;
  media?: T;
  value?: T;
  valueRichText?: T;
  visible?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions_select".
 */
export interface DirectionsSelect<T extends boolean = true> {
  title?: T;
  titleRichText?: T;
  text?: T;
  textRichText?: T;
  media?: T;
  number?: T;
  eyebrow?: T;
  eyebrowRichText?: T;
  slug?: T;
  outcomes?:
    | T
    | {
        text?: T;
        textRichText?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
        points?:
          | T
          | {
              text?: T;
              textRichText?: T;
              id?: T;
            };
        id?: T;
      };
  buttonLabel?: T;
  buttonUrl?: T;
  visible?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        description?: T;
        descriptionRichText?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages_select".
 */
export interface StagesSelect<T extends boolean = true> {
  title?: T;
  titleRichText?: T;
  text?: T;
  textRichText?: T;
  media?: T;
  visible?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  titleRichText?: T;
  text?: T;
  textRichText?: T;
  media?: T;
  author?: T;
  authorRichText?: T;
  company?: T;
  companyRichText?: T;
  role?: T;
  roleRichText?: T;
  visible?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  titleRichText?: T;
  text?: T;
  textRichText?: T;
  media?: T;
  slug?: T;
  client?: T;
  clientRichText?: T;
  metrics?:
    | T
    | {
        value?: T;
        valueRichText?: T;
        label?: T;
        labelRichText?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonUrl?: T;
  visible?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        description?: T;
        descriptionRichText?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  titleRichText?: T;
  text?: T;
  textRichText?: T;
  media?: T;
  slug?: T;
  price?: T;
  features?:
    | T
    | {
        text?: T;
        textRichText?: T;
        id?: T;
      };
  buttonLabel?: T;
  buttonUrl?: T;
  visible?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        description?: T;
        descriptionRichText?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    telegram?: string | null;
    address?: string | null;
  };
  navigation?:
    | {
        label: string;
        url: string;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  colors?: {
    accent?: ('blue' | 'graphite' | 'mono') | null;
    surface?: ('white' | 'cool-gray') | null;
  };
  seoCenter?: {
    /**
     * Например: https://intech.ru
     */
    siteUrl?: string | null;
    siteName?: string | null;
    /**
     * Organization, LocalBusiness или ProfessionalService
     */
    organizationType?: string | null;
    organizationName?: string | null;
    /**
     * По одной ссылке с новой строки
     */
    socialLinks?: string | null;
    /**
     * Ваши строки будут добавлены к стандартным правилам
     */
    robotsText?: string | null;
    /**
     * После сохранения счётчики автоматически появятся на публичных страницах сайта.
     */
    analytics?: {
      /**
       * Только цифры, например 12345678
       */
      yandexMetrikaId?: string | null;
      /**
       * Например G-XXXXXXXXXX
       */
      googleAnalyticsId?: string | null;
      /**
       * Только ID пикселя
       */
      metaPixelId?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    title?: string | null;
    /**
     * H1–H6, жирный, курсив, ссылки и списки. Если заполнен, используется на сайте вместо старого заголовка.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    accent?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    accentRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    message?: string | null;
    /**
     * Если заполнен, используется на сайте вместо старого текста.
     */
    messageRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    video?: (number | null) | Media;
  };
  statement?: {
    eyebrow?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    eyebrowRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  contact?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  seo?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    descriptionRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  seoAdvanced?: {
    /**
     * Основной поисковый запрос для этой страницы
     */
    focusKeyword?: string | null;
    /**
     * По умолчанию H1. На странице должен быть только один H1.
     */
    primaryHeadingTag?: ('h1' | 'h2' | 'h3' | 'p' | 'div') | null;
    /**
     * Через запятую
     */
    keywords?: string | null;
    canonicalUrl?: string | null;
    /**
     * Например: index,follow или noindex,nofollow
     */
    robots?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogUrl?: string | null;
    ogType?: string | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    /**
     * JSON или массив JSON-объектов. Например: Organization, WebSite, Service, FAQPage или LocalBusiness.
     */
    schemaOrg?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-page".
 */
export interface AutomationPage {
  id: number;
  hero?: {
    title?: string | null;
    /**
     * H1–H6, жирный, курсив, ссылки и списки. Если заполнен, используется на сайте вместо старого заголовка.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * Если заполнен, используется на сайте вместо старого описания.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    media?: (number | null) | Media;
    primaryLabel?: string | null;
    primaryUrl?: string | null;
    secondaryLabel?: string | null;
    secondaryUrl?: string | null;
    systemsLine?: string | null;
  };
  sectionHeadings?: {
    problems?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    problemsRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    directions?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    directionsRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cases?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    casesRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    facts?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    factsRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    stages?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    stagesRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    reviews?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    reviewsRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    contact?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    contactRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Карточки блока «Узнаёте один из этих сценариев?»
   */
  problems?:
    | {
        title?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        titleRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        before?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        beforeRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        after?: string | null;
        /**
         * H1–H6, абзацы, ссылки, жирный, курсив и списки.
         */
        afterRichText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  flow?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    items?:
      | {
          text?: string | null;
          /**
           * H1–H6, абзацы, ссылки, жирный, курсив и списки.
           */
          textRichText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          visible?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  directionsIntro?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  casesIntro?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  factsIntro?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  integrations?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    systems?:
      | {
          name?: string | null;
          /**
           * H1–H6, абзацы, ссылки, жирный, курсив и списки.
           */
          nameRichText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          visible?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  stagesIntro?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  formats?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    items?:
      | {
          title?: string | null;
          /**
           * H1–H6, абзацы, ссылки, жирный, курсив и списки.
           */
          titleRichText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          text?: string | null;
          /**
           * H1–H6, абзацы, ссылки, жирный, курсив и списки.
           */
          textRichText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          media?: (number | null) | Media;
          visible?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  pricing?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    subtitle?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    subtitleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    footerText?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    footerTextRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  reviewsIntro?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  faq?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    items?:
      | {
          question?: string | null;
          /**
           * H1–H6, абзацы, ссылки, жирный, курсив и списки.
           */
          questionRichText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          answer?: string | null;
          /**
           * H1–H6, абзацы, ссылки, жирный, курсив и списки.
           */
          answerRichText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          visible?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    accent?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    accentRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    textRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    note?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    noteRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    submitLabel?: string | null;
    successLabel?: string | null;
    telegramLabel?: string | null;
  };
  footer?: {
    tagline?: string | null;
  };
  seo?: {
    title?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    titleRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description?: string | null;
    /**
     * H1–H6, абзацы, ссылки, жирный, курсив и списки.
     */
    descriptionRichText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  seoAdvanced?: {
    /**
     * Основной поисковый запрос для этой страницы
     */
    focusKeyword?: string | null;
    /**
     * По умолчанию H1. На странице должен быть только один H1.
     */
    primaryHeadingTag?: ('h1' | 'h2' | 'h3' | 'p' | 'div') | null;
    /**
     * Через запятую
     */
    keywords?: string | null;
    canonicalUrl?: string | null;
    /**
     * Например: index,follow или noindex,nofollow
     */
    robots?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogUrl?: string | null;
    ogType?: string | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    /**
     * JSON или массив JSON-объектов. Например: Organization, WebSite, Service, FAQPage или LocalBusiness.
     */
    schemaOrg?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  telegram?: {
    enabled?: boolean | null;
    botToken?: string | null;
    chatId?: string | null;
  };
  bitrix24?: {
    enabled?: boolean | null;
    webhookUrl?: string | null;
  };
  amoCrm?: {
    enabled?: boolean | null;
    webhookUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        telegram?: T;
        address?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        visible?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        accent?: T;
        surface?: T;
      };
  seoCenter?:
    | T
    | {
        siteUrl?: T;
        siteName?: T;
        organizationType?: T;
        organizationName?: T;
        socialLinks?: T;
        robotsText?: T;
        analytics?:
          | T
          | {
              yandexMetrikaId?: T;
              googleAnalyticsId?: T;
              metaPixelId?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        accent?: T;
        accentRichText?: T;
        message?: T;
        messageRichText?: T;
        video?: T;
      };
  statement?:
    | T
    | {
        eyebrow?: T;
        eyebrowRichText?: T;
        title?: T;
        titleRichText?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        description?: T;
        descriptionRichText?: T;
        image?: T;
        noIndex?: T;
      };
  seoAdvanced?:
    | T
    | {
        focusKeyword?: T;
        primaryHeadingTag?: T;
        keywords?: T;
        canonicalUrl?: T;
        robots?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogUrl?: T;
        ogType?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        schemaOrg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-page_select".
 */
export interface AutomationPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
        media?: T;
        primaryLabel?: T;
        primaryUrl?: T;
        secondaryLabel?: T;
        secondaryUrl?: T;
        systemsLine?: T;
      };
  sectionHeadings?:
    | T
    | {
        problems?: T;
        problemsRichText?: T;
        directions?: T;
        directionsRichText?: T;
        cases?: T;
        casesRichText?: T;
        facts?: T;
        factsRichText?: T;
        stages?: T;
        stagesRichText?: T;
        reviews?: T;
        reviewsRichText?: T;
        contact?: T;
        contactRichText?: T;
      };
  problems?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        before?: T;
        beforeRichText?: T;
        after?: T;
        afterRichText?: T;
        visible?: T;
        id?: T;
      };
  flow?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
        items?:
          | T
          | {
              text?: T;
              textRichText?: T;
              visible?: T;
              id?: T;
            };
      };
  directionsIntro?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
      };
  casesIntro?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
      };
  factsIntro?:
    | T
    | {
        title?: T;
        titleRichText?: T;
      };
  integrations?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
        systems?:
          | T
          | {
              name?: T;
              nameRichText?: T;
              visible?: T;
              id?: T;
            };
      };
  stagesIntro?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
      };
  formats?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        text?: T;
        textRichText?: T;
        items?:
          | T
          | {
              title?: T;
              titleRichText?: T;
              text?: T;
              textRichText?: T;
              media?: T;
              visible?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        subtitle?: T;
        subtitleRichText?: T;
        footerText?: T;
        footerTextRichText?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  reviewsIntro?:
    | T
    | {
        title?: T;
        titleRichText?: T;
      };
  faq?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        items?:
          | T
          | {
              question?: T;
              questionRichText?: T;
              answer?: T;
              answerRichText?: T;
              visible?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        accent?: T;
        accentRichText?: T;
        text?: T;
        textRichText?: T;
        note?: T;
        noteRichText?: T;
        submitLabel?: T;
        successLabel?: T;
        telegramLabel?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        titleRichText?: T;
        description?: T;
        descriptionRichText?: T;
        image?: T;
        noIndex?: T;
      };
  seoAdvanced?:
    | T
    | {
        focusKeyword?: T;
        primaryHeadingTag?: T;
        keywords?: T;
        canonicalUrl?: T;
        robots?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogUrl?: T;
        ogType?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        schemaOrg?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  telegram?:
    | T
    | {
        enabled?: T;
        botToken?: T;
        chatId?: T;
      };
  bitrix24?:
    | T
    | {
        enabled?: T;
        webhookUrl?: T;
      };
  amoCrm?:
    | T
    | {
        enabled?: T;
        webhookUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}